### ISSUE TITLE
PVPGN 

### ISSUE THREAD

**Issue by interkill** [pvpgn/pvpgn-magic-builder#10]
-- GHost++ (https://github.com/OHSystem/ohsystem)
	ghost = true, -- enable GHost commands
	ghost_bots = {"test" , "test1" , "test2" , "test3" }, -- list of authorized bots
	ghost_dota_server = true, -- replace normal Warcraft 3 stats with DotA
	ghost_ping_expire = 90, -- interval when outdated botpings should be removed (bot ping updates for each user when he join a game hosted by ghost); game list shows to user depending on the best ping to host bot

It only writes at very first, although different names are already written.

Have I made a mistake somewhere?

**Comment by HarpyWar** [comment]
This feature was not finished in ohsystem, therefore it doesn't work.
This issue relates to [PvPGN](https://github.com/pvpgn/pvpgn-server), but not to Magic Builder.
