### ISSUE TITLE
compilation log

### ISSUE THREAD

**Issue by Danteoriginal** [pvpgn/pvpgn-magic-builder#15]
hellow harpywar download log

http://www.mediafire.com/download/0udh17b8mf2l2t5/log.rar

regards

**Comment by HarpyWar** [comment]
I can't figure out what's wrong from these logs - these are not enough. I've tested Magic Builder on both x86 and x64 Windows 10 and it worked without any problems.

May be this error occured due an unfinished Visual Studio installation. Try repeat install to repair it.

If the issue related to https://github.com/pvpgn/pvpgn-server/issues/174 then you should attach two more log files according to the info https://github.com/pvpgn/pvpgn-magic-builder/wiki/Diagnosis-of-problems.
