### ISSUE TITLE
Visual Studio 2015 or high!

### ISSUE THREAD

**Issue by Karaulov** [pvpgn/pvpgn-magic-builder#16]
Please fix CmakeLists.txt "if (MSVC)..." Required Visual Studio 2015 or high!"

**Comment by Karaulov** [comment]
https://github.com/pvpgn/pvpgn-magic-builder/releases/latest

**Comment by xboi209** [comment]
This is a hardcoded requirement to allow PvPGN to take advantage of C++11 features now and in the future. You could remove the check yourself if you want to try to compile PvPGN with VS2013 but no support will be provided if you do so.
