### ISSUE TITLE
1.13d Uber Tristram does not work

### ISSUE THREAD

**Issue by DetectiveSquirrel** [pvpgn/pvpgn-magic-builder#25]
Just got it setup (1.13d D2GS) last week and tried to open Uber portals but nothing happens, am i missing a config option somewhere?

**Comment by HarpyWar** [comment]
I didn't play in D2GS 1.13d. Waiting for someone who can confirm the issue.

**Comment by HarpyWar** [comment]
It seems the truth https://forums.pvpgn.pro/viewtopic.php?id=1733
If somebody knows how to bypass it on 1.13d then let us know.

**Comment by HarpyWar** [comment]
Need feedback for a patch which should fix the problem
https://forums.pvpgn.pro/viewtopic.php?id=2215
