### ISSUE TITLE
magic builder says that i dont have visual studio

### ISSUE THREAD

**Issue by hehpe** [pvpgn/pvpgn-magic-builder#28]
I have downloaded and installed visual studio 2017 community but magic builder say that i don't have visual studio..

**Comment by HarpyWar** [comment]
Visual Studio != Visual C++
Make sure you selected Visual C++ when install. This issue is described in readme of the project.

**Comment by Comfarol** [comment]
![image](https://user-images.githubusercontent.com/27315987/36782004-4587f078-1cc3-11e8-9b1f-b8c178057baf.png)

same

**Comment by RElesgoe** [comment]
Post the output from magic builder

**Comment by Comfarol** [comment]
this error message pops up, when i click close magic build says access is denied visual studio is not installed even though it is. This output you need?
![image](https://user-images.githubusercontent.com/27315987/36815679-388712aa-1d27-11e8-8bf6-061238473ea2.png)

**Comment by HarpyWar** [comment]
Confirmed. The issues occured due to github changed their SSL version and wget, which used by Magic Builder, does not work with the new SSL version.
`vswhere.exe` must be downloaded from github but it has 0 bytes size because of the wget. Therefore the error on the screen.

**Comment by Comfarol** [comment]
Can you update this thread when it gets resolved so I am alerted. Cheers.

**Comment by HarpyWar** [comment]
Fixed. Download the new version.
