### ISSUE TITLE
Magic builder doesn't detect VS2017

### ISSUE THREAD

**Issue by Sweetez** [pvpgn/pvpgn-magic-builder#30]
![image](https://user-images.githubusercontent.com/15938653/34597001-9e40b95c-f216-11e7-8117-d45a4031c459.png)

I installed both of them but did not works.

I don't know where did i mess it up.

**Comment by Sweetez** [comment]
neither %VS160COMNTOOLS% or %VS150COMNTOOLS% works so i dl brand new VS2015 and %VS140COMNTOOLS% now registered. im good now.

**Comment by HarpyWar** [comment]
Visual Studio 2017 does not add environment variables such %VS150COMNTOOLS% or %VS160COMNTOOLS%. It can be detected with https://github.com/Microsoft/vswhere

I tried and it detects fine all Visual Studio 2017 editions from Community to Enterprise.
`vswhere.exe` should be downloaded automatically by Magic Builder automatically on first start. You can run that utility to check is VC++ 2017 installed or not.
