### ISSUE TITLE
MSBUILD : error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by Happin3ss** [pvpgn/pvpgn-magic-builder#31]
Currently I cannot build the project using the magic builder . It seems weird to me because I check that the project file pvpgn.sln is available in build folder but msbuild cannot find it.
 Please take a look in the log file I attached. Thank you so much.

[Log.txt](https://github.com/pvpgn/pvpgn-magic-builder/files/1639666/Log.txt)

**Comment by HarpyWar** [comment]
a) Try re-download Magic Builder from Releases section, but not from Clone or download button (see the issue in the Readme).
b) Possible something wrong with cmake. Try install it from https://cmake.org and let me know if it works. Magic Builder does not download pre-defined cmake if it's already installed.

**Comment by Happin3ss** [comment]
Hi Harpy, thank you for your support.
I got Magic Builder from Release page so I think there is no problem with it. I also used the latest cmake version from cmake.org. The issue seem more strange to me that I can use the msbuild manually to build it. Hmm I will give a try on another PC on tmr and let you know if It work :)

**Comment by Happin3ss** [comment]
The same happened on others PCs :(

**Comment by DronkieGit** [comment]
I'm having the same issue. Any chance this can get looked into asap? :)

**Comment by RElesgoe** [comment]
@DronkieGit Can you post logs?

**Comment by DronkieGit** [comment]
@RElesgoe Where would i find that?

**Comment by DronkieGit** [comment]
https://pastebin.com/Q8CV1nw5

**Comment by HarpyWar** [comment]
I can look into the issue remotely via Teamviewer tomorrow. Write me your ID and Password on harpywar@gmail.com 4 Feb at 8:00 UTC (or 12:00 UTC).

**Comment by DronkieGit** [comment]
@HarpyWar Thanks, but no thanks. I'd rather not have someone i don't know prod around on my pc :) 

If someone else with the same issue wants to do it, i'd love to know if you guys found a fix though.
