### ISSUE TITLE
wget.exe has stopped working error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by Comfarol** [pvpgn/pvpgn-magic-builder#32]
I get this windows error if i choose not to update to latest source on git,  it says "CMake configuration failed" and ends there. 
![image](https://user-images.githubusercontent.com/27315987/36928097-625f2cfe-1ece-11e8-9185-cff2b99ce381.png)

Then when i choose to use the latest from git it shows lots of not found messages and ends with 

MSBUILD : error MSB1009: Project file does not exist.
Switch: build\pvpgn.sln

______________________________[ R E L E A S E ]_________________________________
SOMETHING GONE WRONG :-(
Press any key to continue . . .
![image](https://user-images.githubusercontent.com/27315987/36928716-fdf332d2-1ed3-11e8-9eb8-4440e722a54b.png)

**Comment by HarpyWar** [comment]
There was a problem with download source which I just fixed.
But it looks like your error is the same as here https://github.com/pvpgn/pvpgn-magic-builder/issues/31

Contact with me on harpywar@gmail.com if you can provide Teamviewer access.
