### ISSUE TITLE
failing on checking update and detect visual studio

### ISSUE THREAD

**Issue by three0s** [pvpgn/pvpgn-magic-builder#34]
Did a little bit of digging, seems all networking requests failed. 
![image](https://user-images.githubusercontent.com/9795292/46242143-e1754280-c392-11e8-8fba-83247988ee84.png)

Any ideas how I should proceed? Thanks

Edit: I should also mention that I definitely have visual studio(2017) installed.

**Comment by HarpyWar** [comment]
Something block connections of the program. Check antivirus or firewall, try run it with administrator rights.

**Comment by three0s** [comment]
It's not the firewall. Running it with admin rights changes some of the paths, and I get another error
![image](https://user-images.githubusercontent.com/9795292/46246610-8feaa900-c3ce-11e8-88da-dc2d5555f912.png)

**Comment by HarpyWar** [comment]
Path error may occurs when path to the program contains spaces and utf8 characters. 

What about update check issue, it uses WSH (vbscript) and may be it's disabled somehow in your system https://github.com/pvpgn/pvpgn-magic-builder/blob/master/module/autoupdate/check_for_update.inc.bat#L15
If you run `wscript` from cmd, it opens a window with WSH properties? Try create a new file `test.vbs` with contents `MsgBox("test")` and execute it to make sure it works.

**Comment by three0s** [comment]
Yeah, it seems to work fine. Btw, this was on windows 10. I kinda don't wanna dig into the wget vbscript. 

I managed to get it to work on another PC(the intended server on server 2012). Also ran into the issue where vswhere.exe was not correctly downloaded(0kb file) and had to manually copy one.  I am closing this issue.
