### ISSUE TITLE
Installation problem for windows, no unzip.exe

### ISSUE THREAD

**Issue by tnan** [pvpgn/pvpgn-magic-builder#35]
Hello, I got some problem when they download source.zip for cmake installation. There are no unzip.exe file, then cmake configuration failed! Anyone please help me with this problem!

**Comment by HarpyWar** [comment]
This file is downloaded from https://fossies.org/windows/misc/unz600xn.exe/unzip.exe
Make sure you have a connection to that web site. After the automatic download the file must be located at `module\tools\unzip.exe`
