### ISSUE TITLE
Errors creating pvpgn 2.26

### ISSUE THREAD

**Issue by BinaryNebula** [pvpgn/pvpgn-magic-builder#36]
Getting an error before the Visual Studio build regarding a CMake error. Running Windows 10. Tried modifying the CMake application in the tools folder to under Windows Vista Compatibility mode, like D2 requires, with no luck. The D2gs builder works fine, having issues with the Build_pvpgn batch file. 

______________________________________________________________________________________________________

CMake Error: The source directory "C:/Users/*MyUser*/Desktop/Builder/source" does not appear to contain CMakeLists.txt.

Seems to fail no matter what choices I make even default ones. I selected no to replace latest pvpgn source from git, but have selected Y in previous attempts to make sure I wasn't missing important files. It also fails with or without database support. Tried with MySQL and PostgreSQL.

______________________________[ U P D A T E ]___________________________________
Checking for update ...
"v2.26" is your version
"v2.26" is the latest version

 You have the latest PvPGN Magic Builder

_______________________________[ S E T U P ]____________________________________
"Visual Studio 15 2017" is selected as a build environment

--------------------------------------------------------------------------------
Do you want to download/replace the latest PvPGN source from Git (into "source" directory)?
[Y,N]?N
   PvPGN source code will not be updated

--------------------------------------------------------------------------------
Select PvPGN interface:
   1) Console (defaut)
   2) GUI

Select a number
[1,2]?1
   Set PvPGN interface as Console

--------------------------------------------------------------------------------
Select a database type:
   1) Plain / CDB (default)
   2) MySQL
   3) PostgreSQL
   4) SQLite3
   5) ODBC

Select a number
[1,2,3,4,5]?1
   PvPGN will be built without database support

--------------------------------------------------------------------------------
Enable Lua scripting support?
[Y,N]?N
   PvPGN will be compiled without Lua

_____________________[ P V P G N  S O U R C E  C O D E]_________________________

______________________[ C M A K E  C O N F I G U R E ]__________________________
Visual Studio Locator version 2.3.2+gf154130015 [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 00eed39d
installDate: 9/7/2018 8:24:51 PM
installationName: VisualStudio/15.9.2+28307.108
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.9.28307.108
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.2
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2018-11-21T17:14:25.8393221Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.108
catalog_id: VisualStudio/15.9.2+28307.108
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.2
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 2
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.2+28307.108
catalog_requiredEngineVersion: 1.18.1036.54187
properties_campaignId: Unity3d_Unity
properties_channelManifestId: VisualStudio.15.Release/15.9.2+28307.108
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
The system cannot find the file specified.
'cmake.exe' is not recognized as an internal or external command,
operable program or batch file.

CMake Error: The source directory "C:/Users/*myuser*/Desktop/Builder/source" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

______________[ B U I L D  W I T H  V I S U A L  S T U D I O ]__________________

CMake configuration failed

___________________________[ C O M P L E T E ]__________________________________

**Comment by HarpyWar** [comment]
The Builder updated to support Visual Studio 2019, it should work now.
